---

- name: cisco_find_ip
  hosts: all
  gather_facts: false


  tasks:

   - name: run show access session
     cisco.ios.ios_command:
      commands: show run | include "{{ip_address}}"
     register: output
     
   - name: print output
     debug:
       var: output.stdout_lines
