---

- name: cisco_enable_disable_port
  hosts: "{{ host_name }}"
  gather_facts: false


  tasks:

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ interface }}"
          enabled: False
        state: merged
        config:
        - name: "{{ interface }}"
          enabled: True
        state: merged
