---

- name: cisco_enable_disable_port
  hosts: "{{ host_name }}"
  gather_facts: false


  tasks:

    - name: Shutdown port
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ interface }}"
          enabled: False
        state: merged
        
    - name: pause playbook
      ansible.builtin.pause:
        seconds: 10
        
    - name: No Shutdown port
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ interface }}"
          enabled: true
        state: merged
