---

- name: cisco_configure_trunk_port
  hosts: "{{ host_name }}"
  gather_facts: false


  tasks:

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
       config:
       - name: "{{ port_number }}"
         description: "{{ port_description }}"
       state: merged

    - name: run trunk port configuation
      cisco.ios.ios_l2_interfaces:
       config:
       - name: "{{ port_number }}"
         mode: trunk
         trunk:
           allowed_vlans: "{{ vlan_number }}"
       state: merged