---

- name: cisco_configure_trunk_port
  hosts: "{{ host_name }}"
  gather_facts: false


  tasks:

    - name: run trunk port configuation
      cisco.ios.ios_l2_interfaces:
       config:
       - name: "{{ port_number }}"
         mode: trunk
         trunk:
           allowed_vlans: "{{ vlan_number }}"
           encapsulation: dot1q
      state: merged